Main:
  MMItemsPath: MMItems.yml
  Debug: false
Messages:
  invalidPlayer: §e[EI] §6玩家不在线或不存在
  successInfo: §e[EI] §6成功给予 §f{player} §a{amount} §6个 §f{name}
  givenInfo: §e[EI] §6你得到了 §a{amount} §6个 §f{name}
  dropSuccessInfo: §e[EI] §6成功在 §a{world} §6的 §a{x},{y},{z} §6掉落了 §a{amount} §6个 §f{name}
  unknownItem: §e[EI] §6找不到ID为 §a{itemID} §6的物品
  existedKey: §e[EI] §6已存在ID为 §a{itemID} §6的物品
  onlyPlayer: §e[EI] §6该指令仅可玩家使用
  successSaveInfo: §e[EI] §6成功将 §f{name} §6以ID §a{itemID} §6保存至 §a{path}
  mmImportSuccessInfo: §e[EI] §6成功将所有MM物品保存至 §a{path}
  airItem: §e[EI] §6请不要试图保存空气, 谢谢合作
  invalidAmount: §e[EI] §6无效数字
  invalidWorld: §e[EI] §6无效世界
  invalidLocation: §e[EI] §6无效坐标
  insufficientPermissions: §e[EI] §6权限不足
  reloadedMessage: §e[EI] §6重载完毕
  invalidNBT: §6[EI] §cNBT加载失败, 请勿在列表型NBT中混用键值对, 数字及字符串
  invalidItem: '§6[EI] §c物品加载失败, 物品可能缺损数据, 物品ID: §6{itemID}'
  failureInfo: '§e[EI] §6物品给予失败, 可能原因: 物品未配置材质/玩家已下线'
  invalidMaterial: '§e[EI] §6物品 {itemID} 使用了未知的材质 {material}'
  clickGiveMessage: §e点击获取该物品
Help:
  prefix: |-
    §6====================§eEasyItems§6====================
    §6==================[]为必填, ()为选填==================
  suffix: §6================<< §e{prev} §f{current}§e/§f{total} §e{next} §6>>================
  amount: 10
  format: "{command} §7> {description}"
  prev: 上一页
  next: 下一页
  commands:
    list:
      command: §e/ei §flist (页码)
      description: 查看所有EI物品
    get:
      command: §e/ei §fget [物品ID] (数量)
      description: 根据ID获取EI物品
    give:
      command: §e/ei §fgive [玩家ID] [物品ID] (数量)
      description: 根据ID给予EI物品
    giveAll:
      command: §e/ei §fgiveAll [物品ID] (数量)
      description: 根据ID给予所有人EI物品
    drop:
      command: §e/ei §fdrop [物品ID] [数量] [世界名] [X坐标] [Y坐标] [Z坐标]
      description: 于指定位置掉落EI物品
    save:
      command: §e/ei §fsave [物品ID] (保存路径)
      description: 将手中物品以对应ID保存至对应路径
    cover:
      command: §e/ei §fcover [物品ID] (保存路径)
      description: 将手中物品以对应ID覆盖至对应路径
    mm load:
      command: §e/ei §fmm load [物品ID] (保存路径)
      description: 将对应ID的MM物品保存为EI物品
    mm cover:
      command: §e/ei §fmm cover [物品ID] (保存路径)
      description: 将对应ID的MM物品覆盖为EI物品
    mm loadAll:
      command: §e/ei §fmm loadAll (保存路径)
      description: 将全部MM物品转化为EI物品
    reload:
      command: §e/ei §freload
      description: 重新加载EI物品
    help:
      command: §e/ei §fhelp
      description: 查看帮助信息
ItemList:
  Prefix: §6===========§eEasyItems§6===========
  Suffix: §6======<< §e{prev} §f{current}§e/§f{total} §e{next} §6>>======
  ItemAmount: 10
  ItemFormat: §6{index}. §a{ID} §6- §f{name}
  Prev: 上一页
  Next: 下一页
